default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false

ArmBrain:
    trainer: ppo
    batch_size: 512
    beta: 0.0001
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.0005
    max_steps: 200000
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 200
    summary_freq: 1000
    use_recurrent: false
